#!/bin/bash

set -eux -o pipefail

sudo apt-get install -y rustup cmake build-essential libudev-dev
rustup default stable
rustup component add rust-src rust-analyzer
rustup target add thumbv8m.main-none-eabihf
rustup update

if ! command -v probe-rs
then
    cargo install probe-rs-tools --locked
fi

if ! command -v elf2uf2-rs
then
    cargo install --git https://github.com/JoNil/elf2uf2-rs.git
fi
